### ISSUE TITLE
[v.5.4.69 - 5.4.71] 'DBField' object has no attribute 'calculated'

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#110]
I created a project on v.5.4.62 and it's running fine. But, after upgrading to either 5.4.69, 5.4.70, 5.4.71, I got this error **'DBField' object has no attribute 'calculated'**. 
![error](https://user-images.githubusercontent.com/53944128/62821847-8eb90980-bba5-11e9-962f-3d7a27189388.png)

Note: Windows platform with MSSQL Express 2017.

**Comment by PaulSanZa** [comment]
Seems like it's related to MSSQL. Even I tried to create new items from scratch in Builder, the error still displayed on the console.
![error2](https://user-images.githubusercontent.com/53944128/62822000-aa251400-bba7-11e9-8cc3-076520b4bbee.png)

**Comment by jam-py** [comment]
I fixed this bug. Please upgrade

**Comment by PaulSanZa** [comment]
Hi jam-py,

Thanks. I downloaded the new version. It fixed the 'calculated' but the issue was not fixed completely. I tried creating a new item, after clicked 'Ok' button, the message (as attached) displayed. But, the DB table was created on MSSQL.

![err](https://user-images.githubusercontent.com/53944128/62853278-03ab5100-bd16-11e9-8292-a2bb3e5be795.png)

**Comment by jam-py** [comment]
You know, I can not repeat the bug.
Can you send me the image of the builder when this error happens,
with field have you added. 
Please, try to hard-refresh the browser.

**Comment by PaulSanZa** [comment]
Hi,

I'm not sure whether it's related to 'History'.  I disabled 'History' and re-created the items, it worked just fine. Then, I enabled 'History' and created the items, the error displayed.

**Comment by PaulSanZa** [comment]
This is the way I reproduced. 
1. Go to 'Project' > 'Parameters' > create on folder icon of 'History' and click 'Create history item' > Close the pop-up window.
2. Go to 'Catalogs' and 'New'. Name the item and created 1 field (or more) and 'Ok' (on Item Editor) and the error displayed.
3. Switched to DB, I found the table was created. but it didn't appear on Builder.

Then, I go back to 'Project' > 'Parameters' and clicked 'x' icon of the 'History' and back to 'Catalogs'. I can create items with no error message

**Comment by jam-py** [comment]
Thank you, I repeated it, trying to fix.

**Comment by PaulSanZa** [comment]
I noticed that I will get error message when I saw 'Generator Name' on Item Editor. If it disappears from screen, I can create items. 
![err6](https://user-images.githubusercontent.com/53944128/62858090-91da0400-bd23-11e9-98d0-0c25b1446b98.png)
![err3](https://user-images.githubusercontent.com/53944128/62858095-943c5e00-bd23-11e9-83c0-aa9aeb61c7c7.png)

**Comment by PaulSanZa** [comment]
Oh, I just saw your reply. Thanks.

**Comment by jam-py** [comment]
I fixed this bug. Thank you for your help

**Comment by PaulSanZa** [comment]
It works! Appreciated and thank you so much.
