### ISSUE TITLE
V7, Details are doubling when having more than one

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#265]
[DetailsDoubling.mp4.zip](https://github.com/jam-py/jam-py/files/11865561/DetailsDoubling.mp4.zip)

Two Details, click on second Tab and then back on First Tab - it will make first one as double, triple, etc.

Also, on Item Group/Details, changing Detail order disables Detail from the table AND order is not respected - First Detail should become second, and vice versa.

Regards
D.

**Comment by platipusica** [comment]
Confirmed with v7 Demo:


![Screenshot from 2023-06-26 15-54-20](https://github.com/jam-py/jam-py/assets/9026100/75ff2709-5485-4dd9-b210-f7fa03918d9b)



![Screenshot from 2023-06-26 15-55-02](https://github.com/jam-py/jam-py/assets/9026100/e1318ff7-f0b2-491a-91d5-f00e0f267271)

**Comment by platipusica** [comment]
Any updates?

**Comment by platipusica** [comment]
Still the same on 7.0.14
![Screenshot from 2023-08-08 17-25-17](https://github.com/jam-py/jam-py/assets/9026100/94ba0676-3355-4dda-b6ca-f340127f336a)

**Comment by platipusica** [comment]
Hi Andrew, 
this seems to be fixed, however, there is still an issue with a Virtual Table added as detail.
When VT is added, the Master does not open for Edit. It has empty form and cannot be closed.

**Comment by jam-py** [comment]
Hi, Drazen
Can you send a simple sample project with this problem?

чт, 16 нояб. 2023 г. в 06:04, platipusica ***@***.***>:

**Comment by platipusica** [comment]
This is all in Demo.
Steps:
-create VT in Detail adding Invoices ID field lookup
- add VT to Invoices View/Edit

 Observe.

**Comment by jam-py** [comment]
Hi, Drazen

I realized the problem.
I started working on it and decided to change the behavior of the virtual
tables.
I make it so that they can send requests to the server and those requests
are handled in the server's event handlers.
I remember that Maxwell suggested this idea.

Regards

пт, 17 нояб. 2023 г. в 04:20, platipusica ***@***.***>:

**Comment by platipusica** [comment]
ok

**Comment by jam-py** [comment]
I fixed the bug

пн, 20 нояб. 2023 г. в 05:28, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Something is still not right:
![Screenshot from 2023-11-24 11-58-44](https://github.com/jam-py/jam-py/assets/9026100/20d13804-2378-4ea3-ad10-e397a11ea27a)
![Screenshot from 2023-11-24 11-57-56](https://github.com/jam-py/jam-py/assets/9026100/a49a75d4-61f4-4c3c-97a2-791ded42fd8f)

**Comment by platipusica** [comment]
Have a look in here:
https://github.com/jam-py/jam-py/issues/281

**Comment by jam-py** [comment]
I looked.
There are a lot of images.
But I don't understand what they mean.
Please explain or give me a sample project.

пт, 8 дек. 2023 г. в 05:56, platipusica ***@***.***>:

**Comment by jam-py** [comment]
I see.
I'll try to fix it.
